import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// `interactiveWidget: "resizes-content"` makes mobile browsers shrink the
// layout viewport (not just the visual viewport) when the on-screen
// keyboard opens, so the flex layout below reflows correctly and the
// pinned input stays above the keyboard instead of being covered by it.
// `viewportFit: "cover"` is what makes `env(safe-area-inset-*)` resolve to
// real values (e.g. the bottom input's safe-area padding in Chat.tsx)
// instead of 0 on notched/home-indicator devices.
export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
  interactiveWidget: "resizes-content",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="h-full flex flex-col overflow-hidden">{children}</body>
    </html>
  );
}
